---
title: "Temas"
output:
    html_document: 
        # self_contained: no
        theme: sandstone
---

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(lubridate)

library(reactable)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

source(here::here("code/lib.R"))

knitr::opts_chunk$set(tidy = FALSE, 
                      echo = FALSE,
                      warning = FALSE)
set.seed(1014)
options(digits = 2, scipen = 999)

# Cores: https://colors.muz.li/palette/f9b4ab/fdebd3/264e70/679186/bbd4ce
```

TO DO

Aqui temos todas as votações? Qual a relação entre essas proposições e todas que avançaram na tramitação na câmara?


```{r}
votadas_raw = read_csv(
  here::here("data/proposicoes-afetadas.csv"),
  col_types = cols(
    .default = col_character(),
    data = col_date(format = ""),
    proposicao_ano = col_double()
  )
) %>% janitor::clean_names()

temas = read_csv(here::here("data/temas.csv"), 
                 col_types = cols(
  .default = col_character(),
  ano = col_double(),
  relevancia = col_double()
)) %>% janitor::clean_names()
```

```{r}
temas %>% 
  skimr::skim()

votadas_raw %>% skimr::skim()
```


```{r}
names(votadas_raw)
names(temas)
```

TO DO : Falar com Fabrício sobre diferenças em matches no join via URI e via nomes

```{r}
votadas_raw %>% 
  # left_join(temas, by = c("proposicao_uri" = "uri_proposicao")) %>%
  left_join(temas, by = c("proposicao_sigla_tipo" = "sigla_tipo",
                          "proposicao_numero" = "numero",
                          "proposicao_ano" = "ano")) %>%
  # group_by(proposicao_ano) %>%
  filter(proposicao_ano >= 2003) %>% 
  summarise(cobertura = sum(!is.na(tema)) /n(), n = n())
```

```{r}
votadas = 
  votadas_raw %>% 
  filter(!is.na(proposicao_ano)) %>% 
  left_join(filter(temas, !is.na(ano)), 
            by = c("proposicao_sigla_tipo" = "sigla_tipo",
                          "proposicao_numero" = "numero",
                          "proposicao_ano" = "ano")) %>%
  filter(year(data) >= 2003) 
```

```{r}
data_i = votadas %>% summarise(i = min(data)) %>% pull(i)
data_f = votadas %>% summarise(i = max(data)) %>% pull(i)
n_v = votadas %>% summarise(i = n_distinct(id_votacao)) %>% pull(i)
```

```{r}
pandemia = tibble(inicio = as.Date("2020-02-26"), fim = data_f + days(30))

geom_pandemia = function() {
  geom_rect(
    data = pandemia,
    aes(xmin = inicio, xmax = fim),
    ymin = -Inf,
    ymax = Inf,
    fill = "#ededed",
    alpha = .7,
    inherit.aes = F
  )
}
```

```{r}
votadas %>% 
  mutate(data = floor_date(data, unit = "halfyear")) %>% 
  group_by(data) %>%
  summarise(n = n_distinct(uri_votacao)) %>% 
  # filter(data != max(data)) %>% 
  ggplot(aes( x = data, y = n)) + 
  geom_line() + 
  geom_point() +
  labs(title = "Votações por semestre")
```


```{r}
votadas %>% 
  mutate(data = floor_date(data, unit = "halfyear")) %>% 
  distinct(data, proposicao_id) %>%
  count(data) %>% 
  ggplot(aes( x = data, y = n)) + 
  geom_line() + 
  labs(title = "Proposições afetadas")
```

Tipos mais comuns

```{r}
tipos_api = jsonlite::fromJSON(here::here("data/sigla_tipo_na_api.json"))$dados

tipos = tipos_api %>% 
  select(sigla, nome) %>% 
  arrange(sigla) %>% 
  group_by(sigla) %>% 
  slice(1) 

votadas %>% 
  distinct(proposicao_id, proposicao_sigla_tipo, proposicao_cod_tipo) %>% 
  count(proposicao_sigla_tipo, sort = T) %>% 
  left_join(tipos, by = c("proposicao_sigla_tipo" = "sigla"))
```

```{r}
votadas %>% 
  distinct(proposicao_id, proposicao_sigla_tipo, proposicao_cod_tipo) %>% 
  count(proposicao_sigla_tipo, proposicao_cod_tipo, sort = T)
```

```{r}
selecionadas = votadas %>% 
  filter(proposicao_sigla_tipo %in% c('PEC', 'PL', 'PLP',
                                  'MPV', 'PLV', 'PDL',
                                  'PRC'))
```

```{r}
selecionadas %>% 
  mutate(data = floor_date(data, unit = "halfyear")) %>% 
  distinct(data, proposicao_id) %>%
  count(data) %>% 
  ggplot(aes( x = data, y = n)) + 
  geom_line() + 
  labs(title = "Proposições afetadas, apenas principais tipos")
```

```{r}
temas_principais = selecionadas %>% 
  filter(!is.na(tema)) %>% 
  count(tema) %>% 
  top_n(12, n) %>% 
  pull(tema)

selecionadas = selecionadas %>% 
  mutate(tema_resumido = if_else(tema %in% temas_principais, tema, "Outros")) 

selecionadas %>% 
  mutate(data = floor_date(data, unit = "year")) %>% 
  filter(tema_resumido != "Outros") %>% 
  count(tema_resumido, data) %>% 
  group_by(data) %>% 
  complete(tema_resumido, data, fill = list(n = 0)) %>% 
  mutate(n = n / sum(n)) %>% 
  ggplot(aes(x = data, y = n, color = tema_resumido)) + 
  facet_wrap(~ reorder(tema_resumido, -n, min)) +
  geom_line(size = 1.2, show.legend = F)
  # geom_area(color = "black", show.legend = F)
```


```{r}
library(broom)
coef_lm = function(x, y) {
  d2 = tibble(data = x, prop = y) %>% 
    arrange(data) %>% 
    mutate(i = rank(data)) %>% 
    slice((n() - 5):n())
  m = lm(prop ~ i, data = d2)
  tidy(m) %>% filter(term == "i") %>% pull(estimate)
}

leg_atual = selecionadas %>% 
  filter(data >= '2019-01-01')

temas_principais = leg_atual %>% 
  filter(!is.na(tema)) %>% 
  count(tema) %>% 
  top_n(12, n) %>% 
  pull(tema)

bimestral = leg_atual %>% 
  mutate(data = floor_date(data, unit = "bimonth")) %>% 
  count(tema, data) %>% 
  group_by(data) %>% 
  mutate(prop = n / sum(n)) %>% 
  ungroup() %>% 
  complete(tema, data, fill = list(n = 0, prop = 0)) 

bimestral = bimestral %>% 
  group_by(tema) %>% 
  mutate(coef = coef_lm(data, prop)) 

mais_mudaram = bimestral %>% 
  distinct(tema, coef) %>% 
  ungroup() %>% 
  arrange(coef) %>% 
  slice(c(1:4, n()-4, n())) 

bimestral %>% 
  filter(tema %in% mais_mudaram$tema) %>% 
  ggplot(aes(x = data, y = prop, color = tema)) + 
  geom_pandemia() +
  facet_wrap(~ reorder(tema, -coef), ncol = 3) +
  geom_line(size = 1, show.legend = F) + 
  geom_point(show.legend = F) + 
  theme(panel.grid.minor = element_blank()) + 
  scale_x_date(date_labels = "%b/%y")

```

```{r}

```

