---
title: "Votações"
output:
    html_document: 
        # self_contained: no
        theme: sandstone
---

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(lubridate)

library(reactable)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

source(here::here("code/lib.R"))

knitr::opts_chunk$set(tidy = FALSE, 
                      echo = FALSE,
                      warning = FALSE)
set.seed(1014)
options(digits = 2, scipen = 999)

# Cores: https://colors.muz.li/palette/f9b4ab/fdebd3/264e70/679186/bbd4ce
```


```{r}
votacoes = read_votacoes()
```

```{r}
principais_orgaos = votacoes %>% 
  count(siglaOrgao) %>% 
  top_n(10, n) %>% 
  pull(siglaOrgao)

votacoes = votacoes %>%
  mutate(
    siglaOrgao_simples = if_else(siglaOrgao %in% principais_orgaos, siglaOrgao, "Outros"),
    durante_pandemia = data > pandemia$inicio
  )

votacoes = votacoes %>% 
  mutate(destaque = grepl("DTQ", ultimaAberturaVotacao_descricao))
```

Os dados: 

```{r include=FALSE}
votacoes %>% glimpse()
```

```{r}
data_i = votacoes %>% summarise(i = min(data)) %>% pull(i)
data_f = votacoes %>% summarise(i = max(data)) %>% pull(i)
n_v = votacoes %>% summarise(i = n()) %>% pull(i)
```

```{r}
pandemia = tibble(inicio = as.Date("2020-02-26"), fim = data_f + days(30))

geom_pandemia = function() {
  geom_rect(
    data = pandemia,
    aes(xmin = inicio, xmax = fim),
    ymin = -Inf,
    ymax = Inf,
    fill = "#ededed",
    alpha = .7,
    inherit.aes = F
  )
}
```

### Sobre votações nominais ou não

Abaixo usamos como critério haver placar na votação. Pode não haver dados sobre os votos discriminados dos parlamentares.


### Quantas são as votações?

Temos `r n_v` votações entre `r data_i` e `r data_f`.

```{r}
votacoes %>% 
  mutate(data = floor_date(data, "months")) %>% 
  count(data, nominal) %>% 
  ggplot(aes(x = data, y = n, fill = nominal)) + 
  geom_pandemia() + 
  geom_col(position = position_stack()) + 
  scale_fill_manual(values = c("#F9B4AB", "#679186")) +
  labs(
    title = "Votações nominais ou não"
  )
```

```{r}
votacoes %>%
  filter(nominal) %>%
  mutate(data = floor_date(data, "months")) %>%
  count(data, nominal) %>%
  ggplot(aes(x = data, y = n)) +
  geom_pandemia() +
  geom_col(position = position_stack(), fill = "#679186") +
  labs(title = "Votações nominais")
```

### Onde são as votações?



```{r}
votacoes %>%
  count(siglaOrgao_simples) %>%
  ggplot(aes(x = reorder(siglaOrgao_simples, n), y = n)) +
  geom_col(position = position_stack()) +
  scale_fill_manual(values = c("#F9B4AB", "#679186")) +
  coord_flip() +
  labs(title = "Votações por órgão",
       x = "", 
       y = "Quantidade")
```

```{r}
votacoes %>%
  count(siglaOrgao_simples, nominal) %>%
  ggplot(aes(x = reorder(siglaOrgao_simples, n), y = n, fill = nominal)) +
  geom_col(position = position_stack()) +
  scale_fill_manual(values = c("#F9B4AB", "#679186")) +
  coord_flip() +
  labs(title = "Votações por órgão",
       x = "", 
       y = "Quantidade")
```

```{r}
votacoes %>% 
  filter(nominal) %>% 
  count(siglaOrgao, sort = T) %>% 
  reactable(compact = TRUE)
```

```{r}
votacoes %>%
  count(siglaOrgao_simples, durante_pandemia) %>%
  ggplot(aes(x = reorder(siglaOrgao_simples, n), y = n, fill = durante_pandemia)) +
  geom_col(position = position_stack()) +
  scale_fill_manual(values = c("#bbd4ce", "#679186")) +
  coord_flip() +
  labs(title = "Votações antes e depois do início da pandemia",
       x = "", 
       fill = "Após início\nda pandemia",
       y = "Quantidade")
```

Onde são essas votações depois do início da pandemia?

```{r}
votacoes %>%
  filter(durante_pandemia) %>%
  count(siglaOrgao, sort = T) %>%
  reactable(compact = TRUE)
```


### Destaques

```{r}
votacoes %>% 
  mutate(data = floor_date(data, "months")) %>% 
  count(data, destaque) %>% 
  ggplot(aes(x = data, y = n, fill = destaque)) + 
  geom_pandemia() + 
  geom_col(position = position_fill()) + 
  scale_y_percent() +
  scale_fill_manual(values = c("#f9d6ab", "#679186")) +
  labs(
    title = "Quão comuns são votações de destaques?",
    subtitle = "Destaque se é votação de DTQ",
    y = "Proporção das votações",
    x = "Mês"
  )
```

